Client:
    type: entity
    table: client
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        prenom:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        adresse:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        ville:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        codepostal:
            type: string
            nullable: false
            length: 6
            options:
                fixed: false
        telephone:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        civilite:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        identifiant:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        motdepasse:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
