Panier:
    type: entity
    table: panier
    indexes:
        FK_idClient:
            columns:
                - idClient
        FK_idArticle:
            columns:
                - idArticle
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idclient:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: idClient
        idarticle:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: idArticle
    lifecycleCallbacks: {  }
